FROM node:22-bookworm-slim AS frontend-build
WORKDIR /src/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend/ ./
RUN npm run build

FROM busybox:1.37
COPY --from=frontend-build /src/frontend/dist/spa /srv/frontend
COPY backend /srv/backend
COPY docker-compose.yml /srv/docker-compose.yml
COPY README.md /srv/README.md
