//! Assistant conversation, evidence, and execution contracts.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use crate::diagnostics::OperatorWarning;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
/// Author role assigned to a conversation turn.
pub enum AssistantTurnRole {
    /// A request or follow-up supplied by the end user.
    User,
    /// A response generated by the assistant.
    Assistant,
    /// System-level instructions recorded in the conversation.
    System,
    /// Output returned by a tool invocation.
    Tool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
/// Evidence-verification outcome for an assistant answer.
pub enum AssistantVerificationState {
    /// No verification pass was applicable or executed.
    NotRun,
    /// Every checked claim is supported by the selected evidence.
    Verified,
    /// The evidence supports only a subset of the checked claims.
    PartiallySupported,
    /// Selected evidence contradicts at least one checked claim.
    Conflicting,
    /// Available evidence cannot establish the checked claims.
    InsufficientEvidence,
    /// The verification pass ended with an operational failure.
    Failed,
}

/// Finalizer-owned disposition of the public answer body.
///
/// This is intentionally separate from [`AssistantVerificationState`]: a
/// strict safe fallback is terminal but non-factual, while ordinary grounded
/// prose may be factual-ready even when literal verification was not
/// applicable.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "snake_case")]
pub enum AssistantAnswerDisposition {
    #[default]
    /// No terminal answer disposition has been established.
    NonTerminal,
    /// A finalized factual answer is ready for presentation.
    FactualReady,
    /// A terminal non-factual fallback is ready for presentation.
    SafeFallback,
    /// The turn terminates by requesting clarification from the user.
    Clarification,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Persisted metadata for one assistant conversation.
pub struct AssistantConversation {
    /// Stable conversation identifier.
    pub id: Uuid,
    /// Workspace that owns the conversation.
    pub workspace_id: Uuid,
    /// Knowledge library used by the conversation.
    pub library_id: Uuid,
    /// Principal that opened the conversation, when attributable.
    pub created_by_principal_id: Option<Uuid>,
    /// Optional user-facing conversation title.
    pub title: Option<String>,
    /// Current conversation lifecycle state.
    pub conversation_state: String,
    /// Time at which the conversation was created.
    pub created_at: DateTime<Utc>,
    /// Time of the most recent conversation change.
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Persisted, ordered message within an assistant conversation.
pub struct AssistantTurn {
    /// Stable turn identifier.
    pub id: Uuid,
    /// Conversation containing this turn.
    pub conversation_id: Uuid,
    /// Ordinal position of the turn in its conversation.
    pub turn_index: i32,
    /// Author role represented by this turn.
    pub turn_kind: AssistantTurnRole,
    /// Authenticated principal that authored the turn, when applicable.
    pub author_principal_id: Option<Uuid>,
    /// Plain-text message content.
    pub content_text: String,
    /// Execution that produced or consumed this turn, when present.
    pub execution_id: Option<Uuid>,
    /// Time at which the turn was recorded.
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Persisted execution that resolves one assistant request.
pub struct AssistantExecution {
    /// Stable execution identifier.
    pub id: Uuid,
    /// Workspace in which the execution ran.
    pub workspace_id: Uuid,
    /// Knowledge library queried by the execution.
    pub library_id: Uuid,
    /// Conversation that owns the execution.
    pub conversation_id: Uuid,
    /// Captured context bundle used for this execution.
    pub context_bundle_id: Uuid,
    /// User turn that initiated the execution, when persisted.
    pub request_turn_id: Option<Uuid>,
    /// Assistant turn produced by the execution, when persisted.
    pub response_turn_id: Option<Uuid>,
    /// AI binding selected for the execution, when one was resolved.
    pub binding_id: Option<Uuid>,
    /// Associated agent-runtime execution, when delegated to the runtime.
    pub runtime_execution_id: Option<Uuid>,
    /// Current execution lifecycle state.
    pub lifecycle_state: String,
    /// Pipeline stage currently in progress, if any.
    pub active_stage: Option<String>,
    /// User query submitted for execution.
    pub query_text: String,
    /// Stable failure code for an unsuccessful execution.
    pub failure_code: Option<String>,
    /// Time at which execution processing began.
    pub started_at: DateTime<Utc>,
    /// Terminal completion time, or `None` while still active.
    pub completed_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Ranked citation linking an execution to a retrieved chunk.
pub struct AssistantChunkReference {
    /// Execution that selected the chunk.
    pub execution_id: Uuid,
    /// Referenced chunk identifier.
    pub chunk_id: Uuid,
    /// Position assigned by evidence ranking.
    pub rank: i32,
    /// Relevance score used to rank the chunk.
    pub score: f64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Resolvable location for opening cited source content.
pub struct AssistantContentSourceAccess {
    /// Access mechanism represented by the location.
    pub kind: String,
    /// URI or application link used to open the source.
    pub href: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Ranked citation to a prepared document segment.
pub struct AssistantPreparedSegmentReference {
    /// Execution that selected the segment.
    pub execution_id: Uuid,
    /// Referenced prepared-segment identifier.
    pub segment_id: Uuid,
    /// Document revision containing the segment.
    pub revision_id: Uuid,
    /// Structural block type of the prepared segment.
    pub block_kind: String,
    /// Position assigned by evidence ranking.
    pub rank: i32,
    /// Relevance score used to rank the segment.
    pub score: f64,
    /// Ordered heading hierarchy enclosing the segment.
    pub heading_trail: Vec<String>,
    /// Structural path locating the segment within the revision.
    pub section_path: Vec<String>,
    /// Source document identifier, when available.
    pub document_id: Option<Uuid>,
    /// Display title of the source document, when available.
    pub document_title: Option<String>,
    /// Additional source label or disambiguation hint.
    pub document_hint: Option<String>,
    /// Location for opening the cited source, when resolvable.
    pub source_access: Option<AssistantContentSourceAccess>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Ranked citation to a normalized technical fact.
pub struct AssistantTechnicalFactReference {
    /// Execution that selected the fact.
    pub execution_id: Uuid,
    /// Referenced fact identifier.
    pub fact_id: Uuid,
    /// Document revision from which the fact was extracted.
    pub revision_id: Uuid,
    /// Typed category assigned during fact extraction.
    pub fact_kind: String,
    /// Normalized value used for comparison and matching.
    pub canonical_value: String,
    /// Source-facing value suitable for presentation.
    pub display_value: String,
    /// Position assigned by evidence ranking.
    pub rank: i32,
    /// Relevance score used to rank the fact.
    pub score: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Ranked citation to an entity in the knowledge graph.
pub struct AssistantEntityReference {
    /// Execution that selected the entity.
    pub execution_id: Uuid,
    /// Referenced graph-node identifier.
    pub node_id: Uuid,
    /// Position assigned by evidence ranking.
    pub rank: i32,
    /// Relevance score used to rank the entity.
    pub score: f64,
    /// Human-readable entity label.
    pub label: String,
    /// Graph entity type, when classified.
    pub entity_type: Option<String>,
    /// Concise entity description, when available.
    pub summary: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Ranked citation to a relation in the knowledge graph.
pub struct AssistantRelationReference {
    /// Execution that selected the relation.
    pub execution_id: Uuid,
    /// Referenced graph-edge identifier.
    pub edge_id: Uuid,
    /// Position assigned by evidence ranking.
    pub rank: i32,
    /// Relevance score used to rank the relation.
    pub score: f64,
    /// Relation predicate connecting its endpoint entities.
    pub predicate: String,
    /// Canonical relation statement, when one was produced.
    pub normalized_assertion: Option<String>,
}

/// Cardinality metadata for a user-facing projection of assistant evidence.
///
/// Query execution storage and operator debug endpoints retain the complete
/// evidence set. Interactive UI surfaces may return a deterministic bounded
/// projection and use this summary to report how much durable evidence exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct AssistantReferenceSummary {
    /// Number of durable references available before projection limits.
    pub total_count: usize,
    /// Number of references included in this response.
    pub returned_count: usize,
    /// Whether additional references were omitted from the response.
    pub truncated: bool,
}

/// Structured provenance for a single answer candidate.
///
/// Every field is optional because the clarify branches surface candidates
/// derived from different evidence shapes: a graph-entity probe carries an
/// `entity_id`, a document-derived variant carries a `document_id`, and a
/// label-only variant (e.g. a grouped-reference title) carries none.
/// Callers treat a present id as a stable handle for a follow-up tool call
/// and a missing id as "label only".
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct AssistantAnswerCandidateProvenance {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Graph entity represented by the candidate, when applicable.
    pub entity_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Source document represented by the candidate, when applicable.
    pub document_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Source chunk represented by the candidate, when applicable.
    pub chunk_id: Option<Uuid>,
}

/// One typed disambiguation choice the answer pipeline surfaced alongside a
/// clarifying answer.
///
/// `kind` reuses the existing typed vocabulary where it applies — a graph
/// `node_type` for entity probes, `"document"` for a document-derived variant
/// — so agents can route a follow-up without parsing the prose answer body.
/// `confidence` is `None` when the branch has no ranking signal to expose.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct AssistantAnswerCandidate {
    /// User-facing label for the candidate.
    pub label: String,
    /// Typed candidate category used for follow-up routing.
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Ranking confidence, when the producing branch exposes one.
    pub confidence: Option<f64>,
    /// Stable source identifiers associated with the candidate.
    pub provenance: AssistantAnswerCandidateProvenance,
}

/// Typed clarification metadata attached to a grounded-answer turn.
///
/// The prose answer body stays authoritative for humans; this object is
/// additive machine-readable metadata for agent callers. `required` is
/// `true` only when the turn returned a clarifying answer; otherwise the
/// candidate list is empty and `question` is `None`.
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
pub struct AssistantClarification {
    /// Whether the user must clarify before a factual answer can proceed.
    pub required: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Clarifying question presented to the user.
    pub question: Option<String>,
    #[serde(default)]
    /// Structured choices available for resolving the ambiguity.
    pub answer_candidates: Vec<AssistantAnswerCandidate>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// User-safe explanation of a verification limitation.
pub struct AssistantVerificationWarning {
    /// Stable machine-readable warning code.
    pub code: String,
    /// Human-readable warning description.
    pub message: String,
    /// Prepared segment associated with the warning, when known.
    pub related_segment_id: Option<Uuid>,
    /// Technical fact associated with the warning, when known.
    pub related_fact_id: Option<Uuid>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Timing and identity summary for one runtime pipeline stage.
pub struct AssistantRuntimeStageSummary {
    /// Stable machine-readable stage identifier.
    pub stage_kind: String,
    /// User-facing stage label.
    pub stage_label: String,
    /// Total wall-clock spent in this pipeline stage across its attempts.
    /// `None` for executions recorded before stage timing existed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<u64>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Recorded policy decision made during an assistant execution.
pub struct AssistantPolicyDecisionSummary {
    /// Category of runtime object evaluated by policy.
    pub target_kind: String,
    /// Policy outcome applied to the target.
    pub decision_kind: String,
    /// Stable code explaining the decision.
    pub reason_code: String,
    /// Identifier of the evaluated target.
    pub target_id: String,
    /// Time at which the decision was recorded.
    pub decided_at: DateTime<Utc>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Aggregate policy activity for one runtime execution.
pub struct AssistantPolicySummary {
    /// Number of actions policy allowed.
    pub allow_count: i32,
    /// Number of actions policy rejected.
    pub reject_count: i32,
    /// Number of decisions that terminated execution.
    pub terminate_count: i32,
    /// Most recent policy decisions retained for inspection.
    pub recent_decisions: Vec<AssistantPolicyDecisionSummary>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Execution-state summary reported by the agent runtime.
pub struct AssistantRuntimeSummary {
    /// Stable agent-runtime execution identifier.
    pub runtime_execution_id: Uuid,
    /// Current runtime execution lifecycle state.
    pub lifecycle_state: String,
    /// Runtime stage currently in progress, if any.
    pub active_stage: Option<String>,
    /// Maximum number of runtime turns permitted.
    pub turn_budget: i32,
    /// Number of runtime turns consumed so far.
    pub turn_count: i32,
    /// Maximum number of actions that may execute concurrently.
    pub parallel_action_limit: i32,
    /// Stable failure code for an unsuccessful runtime execution.
    pub failure_code: Option<String>,
    /// Redacted failure detail safe to expose to callers.
    pub failure_summary_redacted: Option<String>,
    /// Aggregate policy decisions made during execution.
    pub policy_summary: AssistantPolicySummary,
    /// Time at which the runtime accepted the execution.
    pub accepted_at: DateTime<Utc>,
    /// Terminal completion time, or `None` while still active.
    pub completed_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Evidence, verification, and runtime metadata attached to an answer.
pub struct AssistantEvidenceBundle {
    /// Ordered chunk citations that directly support the rendered answer.
    pub chunk_references: Vec<AssistantChunkReference>,
    /// Prepared document segments used as structured answer evidence.
    pub prepared_segment_references: Vec<AssistantPreparedSegmentReference>,
    /// Typed facts selected from the evidence plane for this answer.
    pub technical_fact_references: Vec<AssistantTechnicalFactReference>,
    /// Graph entities cited by the answer.
    pub entity_references: Vec<AssistantEntityReference>,
    /// Graph relations cited by the answer.
    pub relation_references: Vec<AssistantRelationReference>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Aggregate counts and truncation metadata for the returned references.
    pub reference_summary: Option<AssistantReferenceSummary>,
    /// Final evidence-verification outcome for the rendered answer.
    pub verification_state: AssistantVerificationState,
    /// Structured verification limitations safe to present to the user.
    pub verification_warnings: Vec<AssistantVerificationWarning>,
    #[serde(default)]
    /// Finalizer-owned outcome of the public answer body.
    pub answer_disposition: AssistantAnswerDisposition,
    /// Typed terminal clarification and its structured choices. This is
    /// included on history evidence so a page reload preserves the same
    /// machine-readable outcome as the live execution response.
    pub clarification: AssistantClarification,
    /// Agent-runtime state associated with the answer.
    pub runtime_summary: AssistantRuntimeSummary,
    /// Ordered summaries of runtime stages observed for the answer.
    pub runtime_stage_summaries: Vec<AssistantRuntimeStageSummary>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Hydrated message presented in assistant conversation history.
pub struct AssistantConversationMessage {
    /// Stable message identifier.
    pub id: Uuid,
    /// Author role represented by the message.
    pub role: AssistantTurnRole,
    /// Plain-text message content.
    pub content: String,
    /// Time at which the message was recorded.
    pub timestamp: DateTime<Utc>,
    /// Execution associated with the message, when applicable.
    pub execution_id: Option<Uuid>,
    /// Answer evidence attached to the message, when available.
    pub evidence: Option<AssistantEvidenceBundle>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Conversation summary shown in assistant session lists.
pub struct AssistantSessionListItem {
    /// Stable conversation identifier.
    pub id: Uuid,
    /// Workspace that owns the conversation.
    pub workspace_id: Uuid,
    /// Knowledge library used by the conversation.
    pub library_id: Uuid,
    /// User-facing conversation title.
    pub title: String,
    /// Time of the most recent conversation change.
    pub updated_at: DateTime<Utc>,
    /// Time at which the conversation was created.
    pub created_at: DateTime<Utc>,
    /// Current conversation lifecycle state.
    pub conversation_state: String,
    /// Number of persisted turns in the conversation.
    pub turn_count: i32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Validated user-facing title for an assistant conversation.
pub struct RenameAssistantSessionRequest {
    /// Non-empty conversation title, bounded to 72 Unicode characters.
    #[schema(min_length = 1, max_length = 72)]
    pub title: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Persisted conversation with its turns and execution records.
pub struct AssistantConversationDetail {
    /// Conversation metadata.
    pub session: AssistantConversation,
    /// Persisted turns ordered within the conversation.
    pub turns: Vec<AssistantTurn>,
    /// Executions associated with the conversation.
    pub executions: Vec<AssistantExecution>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Complete persisted evidence and turn context for one execution.
pub struct AssistantExecutionDetail {
    /// Captured context bundle used for the execution.
    pub context_bundle_id: Uuid,
    /// Core execution record.
    pub execution: AssistantExecution,
    /// Agent-runtime state associated with the execution.
    pub runtime_summary: AssistantRuntimeSummary,
    /// Ordered summaries of runtime stages observed during execution.
    pub runtime_stage_summaries: Vec<AssistantRuntimeStageSummary>,
    /// Request turn that initiated the execution, when available.
    pub request_turn: Option<AssistantTurn>,
    /// Response turn produced by the execution, when available.
    pub response_turn: Option<AssistantTurn>,
    /// Chunk citations persisted with this execution record.
    pub chunk_references: Vec<AssistantChunkReference>,
    /// Structured segment citations persisted with this execution record.
    pub prepared_segment_references: Vec<AssistantPreparedSegmentReference>,
    /// Typed fact citations persisted with this execution record.
    pub technical_fact_references: Vec<AssistantTechnicalFactReference>,
    /// Entity citations retained for execution inspection and replay.
    pub entity_references: Vec<AssistantEntityReference>,
    /// Relation citations retained for execution inspection and replay.
    pub relation_references: Vec<AssistantRelationReference>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    /// Persisted aggregate counts and truncation metadata for all citations.
    pub reference_summary: Option<AssistantReferenceSummary>,
    /// Verification outcome stored when this execution reached its terminal state.
    pub verification_state: AssistantVerificationState,
    /// Structured verification limitations stored with the execution.
    pub verification_warnings: Vec<AssistantVerificationWarning>,
    /// Finalizer-owned typed outcome. Historical rows created before this
    /// field existed deserialize conservatively as `non_terminal`.
    #[serde(default)]
    pub answer_disposition: AssistantAnswerDisposition,
    /// Typed clarification metadata for this turn. Defaults to
    /// `required: false` with no candidates for ordinary answers and for
    /// historical rows created before typed clarification persistence; a
    /// clarify turn populates `question` and `answer_candidates`.
    #[serde(default)]
    pub clarification: AssistantClarification,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Session summary paired with messages ready for conversation rendering.
pub struct AssistantHydratedConversation {
    /// Conversation summary for navigation and status display.
    pub session: AssistantSessionListItem,
    /// Hydrated messages in conversation order.
    pub messages: Vec<AssistantConversationMessage>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Current input-composer state for an assistant workspace.
pub struct AssistantComposerState {
    /// Whether the current draft may be submitted.
    pub can_submit: bool,
    /// Preserved draft text, when present.
    pub draft: Option<String>,
    /// Contextual prompt shown when the composer is empty.
    pub placeholder: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Renderable evidence entry in the assistant workspace.
pub struct AssistantEvidenceItem {
    /// Stable identifier within its evidence category.
    pub id: String,
    /// Primary user-facing evidence label.
    pub label: String,
    /// Supporting detail displayed with the label.
    pub detail: String,
    /// Relevance score, when the evidence source provides one.
    pub score: Option<f64>,
    /// Source document associated with the item, when applicable.
    pub document_id: Option<Uuid>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Named collection of related evidence entries.
pub struct AssistantEvidenceGroup {
    /// Stable group key used by clients.
    pub key: String,
    /// User-facing group label.
    pub label: String,
    /// Evidence entries belonging to the group.
    pub items: Vec<AssistantEvidenceItem>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Presentation state for one assistant pipeline stage.
pub struct AssistantStageItem {
    /// Stable machine-readable stage identifier.
    pub stage_kind: String,
    /// User-facing stage label.
    pub stage_label: String,
    /// Whether this stage is currently running.
    pub active: bool,
    /// Whether this stage completed successfully.
    pub completed: bool,
    /// Whether this stage reached a failed terminal state.
    pub failed: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, utoipa::ToSchema)]
#[serde(rename_all = "camelCase")]
/// Fully assembled state required to render an assistant workspace.
pub struct AssistantWorkspaceSurface {
    /// Conversations available in the workspace.
    pub sessions: Vec<AssistantSessionListItem>,
    /// Conversation currently selected by the user, when any.
    pub active_session_id: Option<Uuid>,
    /// Messages rendered for the active conversation.
    pub messages: Vec<AssistantConversationMessage>,
    /// Pipeline stages rendered for the active execution.
    pub stages: Vec<AssistantStageItem>,
    /// Current message-composer state.
    pub composer: AssistantComposerState,
    /// Evidence grouped for workspace presentation.
    pub evidence_groups: Vec<AssistantEvidenceGroup>,
    /// Operator-safe warnings relevant to the workspace state.
    pub warnings: Vec<OperatorWarning>,
}
