/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness check */
    get: operations['getReadiness']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/version': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Service version */
    get: operations['getVersion']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/tokens': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List API tokens
     * @description Requires `workspace:admin` scope or an `instance_admin` token. Instance admin callers may optionally filter by `workspace_id`; workspace-scoped tokens are implicitly limited to their own workspace even if the query parameter is omitted.
     */
    get: operations['listTokens']
    put?: never
    /** Mint an API token */
    post: operations['createToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/bootstrap-token': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Mint an API token using the bootstrap secret
     * @description Requires a `bootstrap_secret` field in the request body matching the backend
     *     `RJUSTRAG_BOOTSTRAP_TOKEN` or `RUSTRAG_BOOTSTRAP_TOKEN` environment variable.
     *     This route is intended for initial setup when no regular API token exists yet.
     */
    post: operations['createBootstrapToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/tokens/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get API token summary
     * @description Requires `workspace:admin` scope or an `instance_admin` token. Workspace-scoped tokens may only access tokens from their own workspace.
     */
    get: operations['getToken']
    put?: never
    post?: never
    /**
     * Revoke API token
     * @description Requires `workspace:admin` scope or an `instance_admin` token. Workspace-scoped tokens may only revoke tokens from their own workspace.
     */
    delete: operations['revokeToken']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/workspaces': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List workspaces */
    get: operations['listWorkspaces']
    put?: never
    /**
     * Create workspace
     * @description Requires `workspace:admin` scope or an `instance_admin` token.
     */
    post: operations['createWorkspace']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/workspaces/{id}/governance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get workspace governance summary
     * @description Requires `workspace:admin`, `usage:read`, `providers:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access their own workspace.
     */
    get: operations['getWorkspaceGovernance']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List projects */
    get: operations['listProjects']
    put?: never
    /**
     * Create project
     * @description Requires `projects:write`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only create projects in their own workspace.
     */
    post: operations['createProject']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects/{id}/readiness': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get project readiness summary
     * @description Requires `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getProjectReadiness']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/provider-accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List provider accounts */
    get: operations['listProviderAccounts']
    put?: never
    /**
     * Create provider account
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createProviderAccount']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/model-profiles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List model profiles */
    get: operations['listModelProfiles']
    put?: never
    /**
     * Create model profile
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only create profiles in their own workspace, and the provider account must belong to that workspace.
     */
    post: operations['createModelProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/provider-governance/{workspace_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get provider governance summary
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access their own workspace.
     */
    get: operations['getProviderGovernance']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/provider-defaults/{workspace_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get onboarding provider defaults summary
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access their own workspace.
     */
    get: operations['getProviderDefaultsSummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects/{project_id}/defaults': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get project provider defaults
     * @description Requires one of `projects:write`, `documents:read`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getProjectDefaults']
    /**
     * Update project provider defaults
     * @description Requires `projects:write`, `workspace:admin`, or an `instance_admin` token. Validates that any referenced provider account and model profiles belong to the project's workspace. The backend currently persists only chat and embedding default profile ids on the project row; provider account, rerank model, and retrieval/chunk settings are validated and echoed in the response but are not persisted.
     */
    put: operations['updateProjectDefaults']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/integrations/{workspace_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get integrations workspace summary
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access their own workspace. Returns up to 5 example projects and all workspace API tokens.
     */
    get: operations['getIntegrationsWorkspaceSummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/integrations/{workspace_id}/examples': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List example projects for integrations setup
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access their own workspace.
     */
    get: operations['listWorkspaceExampleProjects']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/integrations/{workspace_id}/tokens/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /**
     * Revoke a workspace API token from the integrations surface
     * @description Requires `workspace:admin` scope or an `instance_admin` token. The token must belong to the specified workspace.
     */
    delete: operations['revokeWorkspaceToken']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/integrations-products/{workspace_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get integrations product snapshot
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access their own workspace. Response wraps the snapshot under a top-level `snapshot` field.
     */
    get: operations['getIntegrationsProduct']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/sources': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List sources */
    get: operations['listSources']
    put?: never
    /**
     * Create source
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createSource']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/ingestion-jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List ingestion jobs */
    get: operations['listIngestionJobs']
    put?: never
    /**
     * Create ingestion job
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only create jobs for projects in their own workspace.
     */
    post: operations['createIngestionJob']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/ingestion-jobs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get ingestion job detail
     * @description Requires `documents:read`, `documents:write`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access jobs in their own workspace.
     */
    get: operations['getIngestionJobDetail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/ingestion-jobs/{id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retry an ingestion job
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only retry jobs in their own workspace.
     */
    post: operations['retryIngestionJob']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List documents */
    get: operations['listDocuments']
    put?: never
    /**
     * Create document metadata record
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createDocument']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/content/ingest-text': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Queue plain text for ingestion
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     *
     *     The current backend enqueues an ingestion job and returns its queued lifecycle state; it does not synchronously create a document/chunk result in this response.
     *     Workspace-scoped tokens may only queue jobs for projects in their own workspace.
     */
    post: operations['ingestText']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/content/search-chunks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Lexically search chunks within a project
     * @description Requires one of `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['searchChunks']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/content/embed-project': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate embeddings for project chunks
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     *
     *     If `embedding_model_profile_id` is provided, the backend resolves provider/model from that profile;
     *     otherwise it uses `provider_kind` and `model_name` directly.
     */
    post: operations['embedProjectChunks']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/chunks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List chunks by document or project
     * @description Requires `documents:read`, `workspace:admin`, or an `instance_admin` token.
     */
    get: operations['listChunks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/uploads/ingest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload a UTF-8 text-like file and queue ingestion
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     *
     *     Current implementation only supports UTF-8 text-like uploads. The backend decodes the uploaded body as UTF-8 text, enqueues an ingestion job, and returns the queued job metadata rather than a completed document/chunk result.
     *     Workspace-scoped tokens may only queue jobs for projects in their own workspace.
     *
     *     Expected multipart fields:
     *     - `project_id` (required)
     *     - `source_id` (optional)
     *     - `title` (optional)
     *     - `file` (required)
     */
    post: operations['uploadAndIngest']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/retrieval-runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List retrieval runs */
    get: operations['listRetrievalRuns']
    put?: never
    /**
     * Create a retrieval run record manually
     * @description Requires `query:run`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only create runs for projects in their own workspace.
     */
    post: operations['createRetrievalRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/retrieval-runs/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get retrieval run detail
     * @description Requires `query:run`, `workspace:admin`, `documents:read`, or an `instance_admin` token. Workspace-scoped tokens may only access runs in their own workspace.
     */
    get: operations['getRetrievalRunDetail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run live retrieval + generation query
     * @description Requires `query:run`, `workspace:admin`, or an `instance_admin` token.
     *
     *     The backend combines lexical matching with optional semantic matching based on stored chunk embeddings,
     *     then calls the configured LLM gateway to produce the final answer.
     */
    post: operations['runQuery']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/product/projects/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get product-oriented project overview
     * @description Requires one of `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getProductProjectOverview']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/product/projects/{id}/diagnostics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get project diagnostics
     * @description Requires one of `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getProductProjectDiagnostics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/product/projects/{id}/query-contract': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get product query contract description
     * @description Requires one of `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getProductProjectQueryContract']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/product/documents/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get product-oriented document overview
     * @description Requires `documents:read`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access documents in their own workspace. Usage and cost attribution are currently exposed at project scope because per-document attribution is not persisted yet.
     */
    get: operations['getProductDocumentOverview']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/product/documents/{id}/diagnostics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get document diagnostics
     * @description Requires one of `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access documents in their own workspace.
     */
    get: operations['getProductDocumentDiagnostics']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/graph-products/{project_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get graph product snapshot
     * @description Requires one of `query:run`, `documents:read`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getGraphProduct']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/graph-products/{project_id}/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get graph project summary
     * @description Requires one of `query:run`, `documents:read`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getGraphSummary']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/graph-products/{project_id}/search': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Search graph entities and relations
     * @description Requires one of `query:run`, `documents:read`, `workspace:admin`, or an `instance_admin` token. Query parameter `q` must be non-empty.
     */
    get: operations['searchGraph']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/graph-products/{project_id}/entities/{entity_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get graph entity detail
     * @description Requires one of `query:run`, `documents:read`, `workspace:admin`, or an `instance_admin` token. Workspace-scoped tokens may only access projects in their own workspace.
     */
    get: operations['getGraphEntityDetail']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/graph-products/{project_id}/entities/{entity_id}/subgraph': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a bounded subgraph around an entity
     * @description Requires one of `query:run`, `documents:read`, `workspace:admin`, or an `instance_admin` token. Depth defaults to 1 and must be <= 3.
     */
    get: operations['getGraphSubgraph']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/usage-events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List usage events
     * @description Requires `usage:read`, `workspace:admin`, or an `instance_admin` token.
     */
    get: operations['listUsageEvents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/cost-ledger': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List cost ledger entries
     * @description Requires `usage:read`, `workspace:admin`, or an `instance_admin` token.
     */
    get: operations['listCostLedger']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiErrorBody: {
      error: string
    }
    HealthResponse: {
      /** @example ok */
      status: string
      /** @example rustrag-backend */
      service: string
      /** @example local */
      environment: string
    }
    ReadinessResponse: {
      /** @enum {string} */
      status: 'ready' | 'degraded'
      /** @enum {string} */
      postgres: 'ok' | 'down'
      /** @enum {string} */
      redis: 'ok' | 'down'
    }
    /** @enum {string} */
    HealthState: 'healthy' | 'degraded' | 'failed' | 'unknown'
    VersionResponse: {
      service: string
      /** @example 0.1.0 */
      version: string
      environment: string
    }
    CreateTokenRequest: {
      /** Format: uuid */
      workspace_id?: string | null
      /** @example workspace_api */
      token_kind: string
      /** @example frontend-local */
      label: string
      /**
       * @example [
       *       "documents:read",
       *       "query:run"
       *     ]
       */
      scopes: string[]
    }
    TokenCreateResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id?: string | null
      token_kind: string
      label: string
      /** @description Plaintext token shown only at creation time. */
      token: string
      scopes: string[]
    }
    WorkspaceSummary: {
      /** Format: uuid */
      id: string
      slug: string
      name: string
      /** @example active */
      status: string
    }
    WorkspaceGovernanceSummary: {
      /** Format: uuid */
      id: string
      slug: string
      name: string
      status: string
      projects: number
      provider_accounts: number
      model_profiles: number
      api_tokens: number
      health_state: components['schemas']['HealthState']
      usage: components['schemas']['UsageGovernanceSummary']
    }
    CreateWorkspaceRequest: {
      slug: string
      name: string
    }
    ProjectSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
      description?: string | null
    }
    CreateProjectRequest: {
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
      description?: string | null
    }
    ProjectReadinessSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
      ingestion_jobs: number
      sources: number
      documents: number
      ready_for_query: boolean
      /** @example indexed */
      indexing_state: string
    }
    ProviderAccountSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      /** @example openai */
      provider_kind: string
      label: string
      /** @example active */
      status: string
    }
    CreateProviderAccountRequest: {
      /** Format: uuid */
      workspace_id: string
      provider_kind: string
      label: string
      /** Format: uri */
      api_base_url?: string | null
    }
    ModelProfileSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      /** Format: uuid */
      provider_account_id: string
      /** @example chat */
      profile_kind: string
      /** @example gpt-4.1-mini */
      model_name: string
    }
    CreateModelProfileRequest: {
      /** Format: uuid */
      workspace_id: string
      /** Format: uuid */
      provider_account_id: string
      profile_kind: string
      model_name: string
      temperature?: number | null
      /** Format: int32 */
      max_output_tokens?: number | null
    }
    ProviderGovernanceSummary: {
      /** Format: uuid */
      workspace_id: string
      provider_accounts: components['schemas']['ProviderAccountSummary'][]
      model_profiles: components['schemas']['ModelProfileSummary'][]
      warning?: string | null
    }
    SourceSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** @example upload */
      source_kind: string
      label: string
      /** @example active */
      status: string
    }
    CreateSourceRequest: {
      /** Format: uuid */
      project_id: string
      source_kind: string
      label: string
    }
    IngestionJobSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      trigger_kind: string
      /** @example queued */
      status: string
      /** @example created */
      stage: string
    }
    CreateIngestionJobRequest: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      trigger_kind: string
      requested_by?: string | null
    }
    /** @enum {string} */
    IngestionLifecycleState:
      | 'queued'
      | 'validating'
      | 'running'
      | 'partial'
      | 'completed'
      | 'retryable_failed'
      | 'canceled'
      | 'failed'
    IngestionJobDetail: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      trigger_kind: string
      status: string
      stage: string
      requested_by?: string | null
      error_message?: string | null
      /** Format: date-time */
      started_at?: string | null
      /** Format: date-time */
      finished_at?: string | null
      retryable: boolean
      lifecycle: components['schemas']['IngestionLifecycleState']
    }
    DocumentSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      mime_type?: string | null
      checksum?: string | null
    }
    CreateDocumentRequest: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      mime_type?: string | null
      checksum?: string | null
    }
    IngestTextRequest: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      text: string
    }
    IngestTextResponse: {
      /** Format: uuid */
      ingestion_job_id: string
      /** @description Current ingestion job status, initially `queued`. */
      status: string
      /** @description Current ingestion job stage, initially `queued`. */
      stage: string
    }
    SearchChunksRequest: {
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: int32 */
      top_k?: number | null
    }
    ChunkResult: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      document_id: string
      /** Format: int32 */
      ordinal: number
      content: string
    }
    EmbedProjectChunksRequest: {
      /** Format: uuid */
      project_id: string
      provider_kind: string
      model_name: string
      /** Format: uuid */
      embedding_model_profile_id?: string | null
      /** Format: int64 */
      limit?: number | null
    }
    EmbedProjectChunksResponse: {
      /** Format: uuid */
      project_id: string
      embedded_chunks: number
      provider_kind: string
      model_name: string
    }
    ChunkSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      document_id: string
      /** Format: uuid */
      project_id: string
      /** Format: int32 */
      ordinal: number
      content: string
      /** Format: int32 */
      token_count?: number | null
    }
    UploadIngestResponse: {
      /** Format: uuid */
      ingestion_job_id: string
      external_key: string
      /** @description Current ingestion job status, initially `queued`. */
      status: string
      /** @description Current ingestion job stage, initially `queued`. */
      stage: string
      mime_type?: string | null
    }
    RetrievalRunSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: int32 */
      top_k: number
      response_text?: string | null
      /** @example grounded */
      answer_status: string
      weak_grounding: boolean
    }
    RetrievalRunDetail: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: int32 */
      top_k: number
      response_text?: string | null
      answer_status: string
      weak_grounding: boolean
      references: string[]
      matched_chunk_ids: string[]
      warning?: string | null
      debug_json: {
        [key: string]: unknown
      }
    }
    CreateRetrievalRunRequest: {
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: int32 */
      top_k?: number | null
      response_text?: string | null
    }
    QueryRequest: {
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: uuid */
      embedding_model_profile_id?: string | null
      /** Format: int32 */
      top_k?: number | null
    }
    QueryResponse: {
      /** Format: uuid */
      retrieval_run_id: string
      /** Format: uuid */
      project_id: string
      answer: string
      /**
       * @example [
       *       "document:01958f52-1b41-7e1a-81f0-68bb2ac6df54:chunk:0"
       *     ]
       */
      references: string[]
      /** @example gateway_live */
      mode: string
      /** @example grounded */
      answer_status: string
      weak_grounding: boolean
      warning?: string | null
    }
    UsageGovernanceSummary: {
      /** Format: int64 */
      usage_events: number
      /** Format: int64 */
      prompt_tokens: number
      /** Format: int64 */
      completion_tokens: number
      /** Format: int64 */
      total_tokens: number
      /** Format: double */
      estimated_cost: number
    }
    UsageEventSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id?: string | null
      /** Format: uuid */
      model_profile_id?: string | null
      /** @example query */
      usage_kind: string
      /** Format: int32 */
      prompt_tokens?: number | null
      /** Format: int32 */
      completion_tokens?: number | null
      /** Format: int32 */
      total_tokens?: number | null
      raw_usage_json: {
        [key: string]: unknown
      }
    }
    CostLedgerSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id?: string | null
      /** Format: uuid */
      usage_event_id: string
      provider_kind: string
      model_name: string
      /** @example USD */
      currency: string
      /** Format: double */
      estimated_cost: number
      pricing_snapshot_json: {
        [key: string]: unknown
      }
    }
    BootstrapTokenRequest: {
      /** Format: uuid */
      workspace_id?: string | null
      /** @example workspace_token */
      token_kind: string
      /** @example bootstrap-local */
      label: string
      scopes: string[]
      /** @description Must match the backend bootstrap token environment variable. */
      bootstrap_secret?: string | null
    }
    TokenSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id?: string | null
      token_kind: string
      label: string
      /** @example active */
      status: string
      scopes: string[]
      /** Format: date-time */
      last_used_at?: string | null
      /** Format: date-time */
      created_at: string
      /** Format: date-time */
      updated_at: string
    }
    IntegrationExampleProjectSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
    }
    IntegrationTokenSummary: components['schemas']['TokenSummary']
    IntegrationsWorkspaceSummary: {
      /** Format: uuid */
      workspace_id: string
      example_projects: components['schemas']['IntegrationExampleProjectSummary'][]
      api_tokens: components['schemas']['IntegrationTokenSummary'][]
    }
    ProviderDefaultProfileDto: {
      /** @enum {string} */
      profile_kind: 'chat' | 'embedding' | 'rerank'
      model_name: string
      temperature?: number | null
      /** Format: int32 */
      max_output_tokens?: number | null
    }
    ProviderDefaultTemplateDto: {
      /** @enum {string} */
      provider_kind: 'open_ai' | 'deep_seek' | 'open_ai_compatible'
      label: string
      /** Format: uri */
      api_base_url?: string | null
      chat_profile: components['schemas']['ProviderDefaultProfileDto']
      embedding_profile?: components['schemas']['ProviderDefaultProfileDto'] | null
      rerank_profile?: components['schemas']['ProviderDefaultProfileDto'] | null
    }
    OnboardingDefaultsSummary: {
      /** Format: uuid */
      workspace_id: string
      provider_defaults: components['schemas']['ProviderDefaultTemplateDto'][]
      project_defaults: components['schemas']['ProjectDefaultsDto']
      persistence_state: string
      warning?: string | null
    }
    ProjectDefaultsUpsertRequest: {
      /** Format: uuid */
      provider_account_id?: string | null
      /** Format: uuid */
      chat_model_profile_id?: string | null
      /** Format: uuid */
      embedding_model_profile_id?: string | null
      /** Format: uuid */
      rerank_model_profile_id?: string | null
      /** Format: int32 */
      retrieval_top_k?: number | null
      /** Format: int32 */
      chunk_size?: number | null
      /** Format: int32 */
      chunk_overlap?: number | null
    }
    ProjectDefaultsDto: {
      /** Format: uuid */
      workspace_id: string
      /** Format: uuid */
      project_id?: string | null
      /** Format: uuid */
      provider_account_id?: string | null
      /** Format: uuid */
      chat_model_profile_id?: string | null
      /** Format: uuid */
      embedding_model_profile_id?: string | null
      /** Format: uuid */
      rerank_model_profile_id?: string | null
      /** Format: int32 */
      retrieval_top_k: number
      /** Format: int32 */
      chunk_size: number
      /** Format: int32 */
      chunk_overlap: number
    }
    PlaceholderCapabilityDto: {
      implemented: boolean
      /** @enum {string} */
      status: 'ready' | 'partial' | 'planned'
      reason: string
    }
    CitationReferenceDto: {
      kind: string
      label: string
      /** Format: uuid */
      chunk_id?: string | null
      /** Format: uuid */
      document_id?: string | null
      /** Format: uuid */
      source_id?: string | null
      /** Format: double */
      score?: number | null
    }
    RetrievalDebugMetadataDto: {
      matched_chunk_ids: string[]
      references: string[]
      warning?: string | null
      answer_status: string
      weak_grounding: boolean
    }
    OperationalObservabilityDto: {
      trace_hint: string
      metrics_hint: string
      logging_hint: string
    }
    ProductProjectReadinessDto: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      workspace_id: string
      documents: number
      sources: number
      ingestion_jobs: number
      ready_for_query: boolean
      indexing_state: string
    }
    ProductQueryContractDto: {
      route: string
      method: string
      request_fields: string[]
      response_fields: string[]
      citation_fields: string[]
      debug_fields: string[]
    }
    ProductProjectCapabilitiesDto: {
      query_contract: components['schemas']['PlaceholderCapabilityDto']
      citations: components['schemas']['PlaceholderCapabilityDto']
      retrieval_debug_metadata: components['schemas']['PlaceholderCapabilityDto']
      diagnostics: components['schemas']['PlaceholderCapabilityDto']
    }
    ProductProjectOverviewDto: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
      description?: string | null
      readiness: components['schemas']['ProductProjectReadinessDto']
      query_contract: components['schemas']['ProductQueryContractDto']
      citations: components['schemas']['CitationReferenceDto'][]
      retrieval_debug?: components['schemas']['RetrievalDebugMetadataDto'] | null
      observability: components['schemas']['OperationalObservabilityDto']
      capabilities: components['schemas']['ProductProjectCapabilitiesDto']
    }
    ProductProjectDiagnosticsDto: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      workspace_id: string
      latest_ingestion_job?: components['schemas']['IngestionJobSummary'] | null
      latest_retrieval_run?: components['schemas']['RetrievalRunSummary'] | null
      retrieval_debug?: components['schemas']['RetrievalDebugMetadataDto'] | null
      observability: components['schemas']['OperationalObservabilityDto']
    }
    ProductDocumentCapabilitiesDto: {
      provider_usage_attribution: components['schemas']['PlaceholderCapabilityDto']
      cost_accounting: components['schemas']['PlaceholderCapabilityDto']
      workspace_project_attribution: components['schemas']['PlaceholderCapabilityDto']
      citations: components['schemas']['PlaceholderCapabilityDto']
    }
    ProductDocumentOverviewDto: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      mime_type?: string | null
      checksum?: string | null
      usage: components['schemas']['UsageEventSummary'][]
      costs: components['schemas']['CostLedgerSummary'][]
      capabilities: components['schemas']['ProductDocumentCapabilitiesDto']
    }
    ProductDocumentDiagnosticsDto: {
      /** Format: uuid */
      document_id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      project_workspace_id: string
      ingestion_jobs: components['schemas']['IngestionJobSummary'][]
      citations: components['schemas']['CitationReferenceDto'][]
      usage: components['schemas']['UsageEventSummary'][]
      costs: components['schemas']['CostLedgerSummary'][]
    }
    GraphCoverageSummary: {
      /** Format: uuid */
      project_id: string
      entity_count: number
      relation_count: number
      extraction_runs: number
      status: string
      warning?: string | null
    }
    GraphEntitySummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      canonical_name: string
      entity_type?: string | null
      source_chunk_count: number
    }
    GraphRelationSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      relation_type: string
      /** Format: uuid */
      from_entity_id: string
      /** Format: uuid */
      to_entity_id: string
      source_chunk_count: number
    }
    GraphProductSnapshot: {
      /** Format: uuid */
      project_id: string
      coverage: components['schemas']['GraphCoverageSummary']
      entities: components['schemas']['GraphEntitySummary'][]
      relations: components['schemas']['GraphRelationSummary'][]
      /** Format: date-time */
      generated_at: string
    }
    GraphProductResponse: {
      snapshot: components['schemas']['GraphProductSnapshot']
    }
    GraphKindCount: {
      name: string
      count: number
    }
    GraphProjectSummaryResponse: {
      /** Format: uuid */
      project_id: string
      coverage: components['schemas']['GraphCoverageSummary']
      entity_kinds: components['schemas']['GraphKindCount'][]
      relation_kinds: components['schemas']['GraphKindCount'][]
      top_entities: components['schemas']['GraphEntitySummary'][]
      sample_relations: components['schemas']['GraphRelationSummary'][]
      /** Format: date-time */
      generated_at: string
    }
    GraphEntitySearchHit: {
      entity: components['schemas']['GraphEntitySummary']
      match_reasons: string[]
    }
    GraphRelationSearchHit: {
      relation: components['schemas']['GraphRelationSummary']
      from_entity_name: string
      to_entity_name: string
      match_reasons: string[]
    }
    GraphSearchResponse: {
      /** Format: uuid */
      project_id: string
      query: string
      searched_fields: string[]
      result_count: number
      entity_results: components['schemas']['GraphEntitySearchHit'][]
      relation_results: components['schemas']['GraphRelationSearchHit'][]
      /** Format: date-time */
      generated_at: string
      warning?: string | null
    }
    GraphRelationDetail: {
      relation: components['schemas']['GraphRelationSummary']
      from_entity_name: string
      to_entity_name: string
    }
    GraphEntityDetailResponse: {
      /** Format: uuid */
      project_id: string
      entity: components['schemas']['GraphEntitySummary']
      aliases: string[]
      source_document_ids: string[]
      source_chunk_ids: string[]
      observed_relation_count: number
      incoming_relations: components['schemas']['GraphRelationDetail'][]
      outgoing_relations: components['schemas']['GraphRelationDetail'][]
      /** Format: date-time */
      generated_at: string
      warning?: string | null
    }
    GraphSubgraphResponse: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      focus_entity_id: string
      depth: number
      entity_count: number
      relation_count: number
      entities: components['schemas']['GraphEntitySummary'][]
      relations: components['schemas']['GraphRelationDetail'][]
      /** Format: date-time */
      generated_at: string
      warning?: string | null
    }
    IntegrationsProductSnapshot: {
      /** Format: uuid */
      workspace_id: string
      provider_accounts: components['schemas']['ProviderAccountSummary'][]
      model_profiles: components['schemas']['ModelProfileSummary'][]
      projects: components['schemas']['ProjectSummary'][]
      available_scopes: string[]
      /** Format: date-time */
      generated_at: string
      warning?: string | null
    }
    IntegrationsProductResponse: {
      snapshot: components['schemas']['IntegrationsProductSnapshot']
    }
  }
  responses: {
    /** @description Bad request */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
      }
    }
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        'WWW-Authenticate'?: string
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
        'text/plain': string
      }
    }
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
      }
    }
    /** @description Conflict */
    Conflict: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
      }
    }
    /** @description Internal server error */
    InternalError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
        'text/plain': string
      }
    }
  }
  parameters: {
    id: string
    workspaceId: string
    projectIdOptional: string
    documentId: string
    limit: number
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service health */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  getReadiness: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Readiness probe result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
    }
  }
  getVersion: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service version metadata */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VersionResponse']
        }
      }
    }
  }
  listTokens: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Visible API token summaries */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenSummary'][]
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  createToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTokenRequest']
      }
    }
    responses: {
      /** @description Newly minted API token */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenCreateResponse']
        }
      }
      400: components['responses']['BadRequest']
      500: components['responses']['InternalError']
    }
  }
  createBootstrapToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['BootstrapTokenRequest']
      }
    }
    responses: {
      /** @description Newly minted API token */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenCreateResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  getToken: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Token summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenSummary']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  revokeToken: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Token revoked */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listWorkspaces: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Workspace list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createWorkspace: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorkspaceRequest']
      }
    }
    responses: {
      /** @description Created workspace */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  getWorkspaceGovernance: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Workspace governance summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceGovernanceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listProjects: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createProject: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest']
      }
    }
    responses: {
      /** @description Created project */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  getProjectReadiness: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project readiness summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectReadinessSummary']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listProviderAccounts: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Provider account list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderAccountSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createProviderAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProviderAccountRequest']
      }
    }
    responses: {
      /** @description Created provider account */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderAccountSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listModelProfiles: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Model profile list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelProfileSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createModelProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateModelProfileRequest']
      }
    }
    responses: {
      /** @description Created model profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelProfileSummary']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProviderGovernance: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Provider governance summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderGovernanceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  getProviderDefaultsSummary: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Workspace onboarding defaults summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['OnboardingDefaultsSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  getProjectDefaults: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project defaults */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectDefaultsDto']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  updateProjectDefaults: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectDefaultsUpsertRequest']
      }
    }
    responses: {
      /** @description Updated project defaults */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectDefaultsDto']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getIntegrationsWorkspaceSummary: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Workspace integrations summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationsWorkspaceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listWorkspaceExampleProjects: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Example project list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationExampleProjectSummary'][]
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  revokeWorkspaceToken: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Token revoked */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getIntegrationsProduct: {
    parameters: {
      query?: never
      header?: never
      path: {
        workspace_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Integrations product snapshot */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IntegrationsProductResponse']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listSources: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Source list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SourceSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createSource: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSourceRequest']
      }
    }
    responses: {
      /** @description Created source */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SourceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listIngestionJobs: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ingestion job list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionJobSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createIngestionJob: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateIngestionJobRequest']
      }
    }
    responses: {
      /** @description Created ingestion job */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionJobSummary']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getIngestionJobDetail: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ingestion job detail */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionJobDetail']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  retryIngestionJob: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Newly created retry ingestion job detail */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionJobDetail']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listDocuments: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Document list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createDocument: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDocumentRequest']
      }
    }
    responses: {
      /** @description Created document */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentSummary']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  ingestText: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IngestTextRequest']
      }
    }
    responses: {
      /** @description Ingestion job accepted and queued */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestTextResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      500: components['responses']['InternalError']
    }
  }
  searchChunks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchChunksRequest']
      }
    }
    responses: {
      /** @description Matching chunk list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChunkResult'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  embedProjectChunks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmbedProjectChunksRequest']
      }
    }
    responses: {
      /** @description Embedding job result summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmbedProjectChunksResponse']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listChunks: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
        document_id?: components['parameters']['documentId']
        limit?: components['parameters']['limit']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Chunk list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChunkSummary'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  uploadAndIngest: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: uuid */
          project_id: string
          /** Format: uuid */
          source_id?: string
          title?: string
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description Ingestion job accepted and queued for the uploaded file */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UploadIngestResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      409: components['responses']['Conflict']
      500: components['responses']['InternalError']
    }
  }
  listRetrievalRuns: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Retrieval run list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RetrievalRunSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createRetrievalRun: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRetrievalRunRequest']
      }
    }
    responses: {
      /** @description Created retrieval run */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RetrievalRunSummary']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getRetrievalRunDetail: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Retrieval run detail */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RetrievalRunDetail']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  runQuery: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['QueryRequest']
      }
    }
    responses: {
      /** @description Query result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['QueryResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProductProjectOverview: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project overview with readiness, query contract, citations, and capability hints */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductProjectOverviewDto']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProductProjectDiagnostics: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project diagnostics */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductProjectDiagnosticsDto']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProductProjectQueryContract: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Query contract descriptor */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductQueryContractDto']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProductDocumentOverview: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Document overview */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductDocumentOverviewDto']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getProductDocumentDiagnostics: {
    parameters: {
      query?: never
      header?: never
      path: {
        id: components['parameters']['id']
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Document diagnostics */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProductDocumentDiagnosticsDto']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getGraphProduct: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Graph snapshot */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GraphProductResponse']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getGraphSummary: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Graph summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GraphProjectSummaryResponse']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  searchGraph: {
    parameters: {
      query: {
        q: string
        limit?: number
      }
      header?: never
      path: {
        project_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Graph search results */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GraphSearchResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getGraphEntityDetail: {
    parameters: {
      query?: never
      header?: never
      path: {
        project_id: string
        entity_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Graph entity detail */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GraphEntityDetailResponse']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  getGraphSubgraph: {
    parameters: {
      query?: {
        depth?: number
      }
      header?: never
      path: {
        project_id: string
        entity_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Graph subgraph response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GraphSubgraphResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listUsageEvents: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Usage event list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsageEventSummary'][]
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listCostLedger: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cost ledger entry list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CostLedgerSummary'][]
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
}
