/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health check */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness check */
    get: operations['getReadiness']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/version': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Service version */
    get: operations['getVersion']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/auth/tokens': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Mint an API token */
    post: operations['createToken']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/workspaces': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List workspaces */
    get: operations['listWorkspaces']
    put?: never
    /**
     * Create workspace
     * @description Requires `workspace:admin` scope or an `instance_admin` token.
     */
    post: operations['createWorkspace']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/projects': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List projects */
    get: operations['listProjects']
    put?: never
    /**
     * Create project
     * @description Requires `projects:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createProject']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/provider-accounts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List provider accounts */
    get: operations['listProviderAccounts']
    put?: never
    /**
     * Create provider account
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createProviderAccount']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/model-profiles': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List model profiles */
    get: operations['listModelProfiles']
    put?: never
    /**
     * Create model profile
     * @description Requires `providers:admin`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createModelProfile']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/sources': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List sources */
    get: operations['listSources']
    put?: never
    /**
     * Create source
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createSource']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/ingestion-jobs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List ingestion jobs */
    get: operations['listIngestionJobs']
    put?: never
    /**
     * Create ingestion job
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createIngestionJob']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/documents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List documents */
    get: operations['listDocuments']
    put?: never
    /**
     * Create document metadata record
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['createDocument']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/content/ingest-text': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Ingest plain text and create chunks
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['ingestText']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/content/search-chunks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Lexically search chunks within a project
     * @description Requires one of `documents:read`, `query:run`, `workspace:admin`, or an `instance_admin` token.
     */
    post: operations['searchChunks']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/content/embed-project': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate embeddings for project chunks
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     *
     *     If `embedding_model_profile_id` is provided, the backend resolves provider/model from that profile;
     *     otherwise it uses `provider_kind` and `model_name` directly.
     */
    post: operations['embedProjectChunks']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/chunks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List chunks by document or project
     * @description Requires `documents:read`, `workspace:admin`, or an `instance_admin` token.
     */
    get: operations['listChunks']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/uploads/ingest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Upload a UTF-8 text-like file and ingest it
     * @description Requires `documents:write`, `workspace:admin`, or an `instance_admin` token.
     *
     *     Current implementation only supports UTF-8 text-like uploads. Expected multipart fields:
     *     - `project_id` (required)
     *     - `source_id` (optional)
     *     - `title` (optional)
     *     - `file` (required)
     */
    post: operations['uploadAndIngest']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/retrieval-runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List retrieval runs */
    get: operations['listRetrievalRuns']
    put?: never
    /**
     * Create a retrieval run record manually
     * @description Auth header is currently required by the handler, but no scope check is enforced.
     */
    post: operations['createRetrievalRun']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Run live retrieval + generation query
     * @description Requires `query:run`, `workspace:admin`, or an `instance_admin` token.
     *
     *     The backend combines lexical matching with optional semantic matching based on stored chunk embeddings,
     *     then calls the configured LLM gateway to produce the final answer.
     */
    post: operations['runQuery']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/usage-events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List usage events
     * @description Requires `usage:read`, `workspace:admin`, or an `instance_admin` token.
     */
    get: operations['listUsageEvents']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/cost-ledger': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List cost ledger entries
     * @description Requires `usage:read`, `workspace:admin`, or an `instance_admin` token.
     */
    get: operations['listCostLedger']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    ApiErrorBody: {
      error: string
    }
    HealthResponse: {
      /** @example ok */
      status: string
      /** @example rustrag-backend */
      service: string
      /** @example local */
      environment: string
    }
    ReadinessResponse: {
      /** @enum {string} */
      status: 'ready' | 'degraded'
      /** @enum {string} */
      postgres: 'ok' | 'down'
      /** @enum {string} */
      redis: 'ok' | 'down'
    }
    VersionResponse: {
      service: string
      /** @example 0.1.0 */
      version: string
      environment: string
    }
    CreateTokenRequest: {
      /** Format: uuid */
      workspace_id?: string | null
      /** @example workspace_api */
      token_kind: string
      /** @example frontend-local */
      label: string
      /**
       * @example [
       *       "documents:read",
       *       "query:run"
       *     ]
       */
      scopes: string[]
    }
    TokenCreateResponse: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id?: string | null
      token_kind: string
      label: string
      /** @description Plaintext token shown only at creation time. */
      token: string
      scopes: string[]
    }
    WorkspaceSummary: {
      /** Format: uuid */
      id: string
      slug: string
      name: string
      /** @example active */
      status: string
    }
    CreateWorkspaceRequest: {
      slug: string
      name: string
    }
    ProjectSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
      description?: string | null
    }
    CreateProjectRequest: {
      /** Format: uuid */
      workspace_id: string
      slug: string
      name: string
      description?: string | null
    }
    ProviderAccountSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      /** @example openai */
      provider_kind: string
      label: string
      /** @example active */
      status: string
    }
    CreateProviderAccountRequest: {
      /** Format: uuid */
      workspace_id: string
      provider_kind: string
      label: string
      /** Format: uri */
      api_base_url?: string | null
    }
    ModelProfileSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      workspace_id: string
      /** Format: uuid */
      provider_account_id: string
      /** @example chat */
      profile_kind: string
      /** @example gpt-4.1-mini */
      model_name: string
    }
    CreateModelProfileRequest: {
      /** Format: uuid */
      workspace_id: string
      /** Format: uuid */
      provider_account_id: string
      profile_kind: string
      model_name: string
      temperature?: number | null
      /** Format: int32 */
      max_output_tokens?: number | null
    }
    SourceSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** @example upload */
      source_kind: string
      label: string
      /** @example active */
      status: string
    }
    CreateSourceRequest: {
      /** Format: uuid */
      project_id: string
      source_kind: string
      label: string
    }
    IngestionJobSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      trigger_kind: string
      /** @example queued */
      status: string
      /** @example created */
      stage: string
    }
    CreateIngestionJobRequest: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      trigger_kind: string
      requested_by?: string | null
    }
    DocumentSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      mime_type?: string | null
      checksum?: string | null
    }
    CreateDocumentRequest: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      mime_type?: string | null
      checksum?: string | null
    }
    IngestTextRequest: {
      /** Format: uuid */
      project_id: string
      /** Format: uuid */
      source_id?: string | null
      external_key: string
      title?: string | null
      text: string
    }
    IngestTextResponse: {
      /** Format: uuid */
      document_id: string
      chunk_count: number
    }
    SearchChunksRequest: {
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: int32 */
      top_k?: number | null
    }
    ChunkResult: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      document_id: string
      /** Format: int32 */
      ordinal: number
      content: string
    }
    EmbedProjectChunksRequest: {
      /** Format: uuid */
      project_id: string
      provider_kind: string
      model_name: string
      /** Format: uuid */
      embedding_model_profile_id?: string | null
      /** Format: int64 */
      limit?: number | null
    }
    EmbedProjectChunksResponse: {
      /** Format: uuid */
      project_id: string
      embedded_chunks: number
      provider_kind: string
      model_name: string
    }
    ChunkSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      document_id: string
      /** Format: uuid */
      project_id: string
      /** Format: int32 */
      ordinal: number
      content: string
      /** Format: int32 */
      token_count?: number | null
    }
    UploadIngestResponse: {
      /** Format: uuid */
      document_id: string
      external_key: string
      chunk_count: number
      mime_type?: string | null
    }
    RetrievalRunSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: int32 */
      top_k: number
      response_text?: string | null
    }
    CreateRetrievalRunRequest: {
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: int32 */
      top_k?: number | null
      response_text?: string | null
    }
    QueryRequest: {
      /** Format: uuid */
      project_id: string
      query_text: string
      /** Format: uuid */
      model_profile_id?: string | null
      /** Format: uuid */
      embedding_model_profile_id?: string | null
      /** Format: int32 */
      top_k?: number | null
    }
    QueryResponse: {
      /** Format: uuid */
      retrieval_run_id: string
      /** Format: uuid */
      project_id: string
      answer: string
      /**
       * @example [
       *       "document:01958f52-1b41-7e1a-81f0-68bb2ac6df54:chunk:0"
       *     ]
       */
      references: string[]
      /** @example gateway_live */
      mode: string
    }
    UsageEventSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id?: string | null
      /** Format: uuid */
      model_profile_id?: string | null
      /** @example query */
      usage_kind: string
      /** Format: int32 */
      prompt_tokens?: number | null
      /** Format: int32 */
      completion_tokens?: number | null
      /** Format: int32 */
      total_tokens?: number | null
      raw_usage_json: {
        [key: string]: unknown
      }
    }
    CostLedgerSummary: {
      /** Format: uuid */
      id: string
      /** Format: uuid */
      project_id?: string | null
      /** Format: uuid */
      usage_event_id: string
      provider_kind: string
      model_name: string
      /** @example USD */
      currency: string
      /** Format: double */
      estimated_cost: number
      pricing_snapshot_json: {
        [key: string]: unknown
      }
    }
  }
  responses: {
    /** @description Bad request */
    BadRequest: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
      }
    }
    /** @description Unauthorized */
    Unauthorized: {
      headers: {
        'WWW-Authenticate'?: string
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
        'text/plain': string
      }
    }
    /** @description Resource not found */
    NotFound: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
      }
    }
    /** @description Internal server error */
    InternalError: {
      headers: {
        [name: string]: unknown
      }
      content: {
        'application/json': components['schemas']['ApiErrorBody']
        'text/plain': string
      }
    }
  }
  parameters: {
    workspaceId: string
    projectIdOptional: string
    documentId: string
    limit: number
  }
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service health */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  getReadiness: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Readiness probe result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
    }
  }
  getVersion: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Service version metadata */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VersionResponse']
        }
      }
    }
  }
  createToken: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateTokenRequest']
      }
    }
    responses: {
      /** @description Newly minted API token */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenCreateResponse']
        }
      }
      400: components['responses']['BadRequest']
      500: components['responses']['InternalError']
    }
  }
  listWorkspaces: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Workspace list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createWorkspace: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWorkspaceRequest']
      }
    }
    responses: {
      /** @description Created workspace */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WorkspaceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listProjects: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Project list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createProject: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProjectRequest']
      }
    }
    responses: {
      /** @description Created project */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProjectSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listProviderAccounts: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Provider account list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderAccountSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createProviderAccount: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProviderAccountRequest']
      }
    }
    responses: {
      /** @description Created provider account */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ProviderAccountSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listModelProfiles: {
    parameters: {
      query?: {
        workspace_id?: components['parameters']['workspaceId']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Model profile list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelProfileSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createModelProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateModelProfileRequest']
      }
    }
    responses: {
      /** @description Created model profile */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ModelProfileSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listSources: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Source list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SourceSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createSource: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateSourceRequest']
      }
    }
    responses: {
      /** @description Created source */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SourceSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listIngestionJobs: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Ingestion job list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionJobSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createIngestionJob: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateIngestionJobRequest']
      }
    }
    responses: {
      /** @description Created ingestion job */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestionJobSummary']
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listDocuments: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Document list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createDocument: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateDocumentRequest']
      }
    }
    responses: {
      /** @description Created document */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DocumentSummary']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  ingestText: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['IngestTextRequest']
      }
    }
    responses: {
      /** @description Text ingested and chunked */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['IngestTextResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  searchChunks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SearchChunksRequest']
      }
    }
    responses: {
      /** @description Matching chunk list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChunkResult'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  embedProjectChunks: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EmbedProjectChunksRequest']
      }
    }
    responses: {
      /** @description Embedding job result summary */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EmbedProjectChunksResponse']
        }
      }
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listChunks: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
        document_id?: components['parameters']['documentId']
        limit?: components['parameters']['limit']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Chunk list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ChunkSummary'][]
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  uploadAndIngest: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': {
          /** Format: uuid */
          project_id: string
          /** Format: uuid */
          source_id?: string
          title?: string
          /** Format: binary */
          file: string
        }
      }
    }
    responses: {
      /** @description Uploaded file ingested successfully */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UploadIngestResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listRetrievalRuns: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Retrieval run list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RetrievalRunSummary'][]
        }
      }
      500: components['responses']['InternalError']
    }
  }
  createRetrievalRun: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRetrievalRunRequest']
      }
    }
    responses: {
      /** @description Created retrieval run */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RetrievalRunSummary']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  runQuery: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['QueryRequest']
      }
    }
    responses: {
      /** @description Query result */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['QueryResponse']
        }
      }
      400: components['responses']['BadRequest']
      401: components['responses']['Unauthorized']
      404: components['responses']['NotFound']
      500: components['responses']['InternalError']
    }
  }
  listUsageEvents: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Usage event list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UsageEventSummary'][]
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
  listCostLedger: {
    parameters: {
      query?: {
        project_id?: components['parameters']['projectIdOptional']
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Cost ledger entry list */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CostLedgerSummary'][]
        }
      }
      401: components['responses']['Unauthorized']
      500: components['responses']['InternalError']
    }
  }
}
